name: (optional) Send MLB Contender Matchups Newsletter

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 15 * * *"   # 15:00 UTC = 23:00 MYT

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          NEWS_RECIPIENTS: ${{ secrets.NEWS_RECIPIENTS }}
        run: |
          python main.py
